package br.org.colheita.infrastructure.persistence;

import br.org.colheita.application.port.out.CatalogPort;
import br.org.colheita.domain.exception.DomainException;
import br.org.colheita.domain.model.CatalogModels.*;
import br.org.colheita.domain.model.PageResult;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.time.Instant;
import java.util.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
public class CatalogJdbcAdapter implements CatalogPort {
    private final JdbcClient jdbc;
    public CatalogJdbcAdapter(JdbcClient jdbc){this.jdbc=jdbc;}
    private String q(String search){return search==null?"":search.trim();}
    @Override public PageResult<Product> listProducts(UUID org,String search,int page,int size){String q=q(search);long total=count("products",org,q,"name","slug");var items=jdbc.sql("SELECT id,slug,name,unit,active FROM colheita.products WHERE organization_id=:org AND (:q='' OR name ILIKE '%'||:q||'%' OR slug ILIKE '%'||:q||'%') ORDER BY name LIMIT :size OFFSET :offset").param("org",org).param("q",q).param("size",size).param("offset",page*size).query((rs,n)->new Product(rs.getObject("id",UUID.class),rs.getString("slug"),rs.getString("name"),rs.getString("unit"),rs.getBoolean("active"))).list();return new PageResult<>(items,total,page,size);}
    @Override public Product saveProduct(UUID org,UUID id,String slug,String name,String unit,boolean active){UUID result=id==null?jdbc.sql("INSERT INTO colheita.products(organization_id,slug,name,unit,active) VALUES(:org,:slug,:name,:unit,:active) RETURNING id").param("org",org).param("slug",slug).param("name",name).param("unit",unit).param("active",active).query(UUID.class).single():updateId("products",org,id,Map.of("slug",slug,"name",name,"unit",unit,"active",active));return product(org,result);}
    private Product product(UUID org,UUID id){return jdbc.sql("SELECT id,slug,name,unit,active FROM colheita.products WHERE organization_id=:org AND id=:id").param("org",org).param("id",id).query((rs,n)->new Product(rs.getObject("id",UUID.class),rs.getString("slug"),rs.getString("name"),rs.getString("unit"),rs.getBoolean("active"))).optional().orElseThrow(()->DomainException.notFound("Produto não encontrado."));}
    @Override public PageResult<School> listSchools(UUID org,String search,int page,int size){String q=q(search);long total=count("schools",org,q,"name","code");var items=jdbc.sql("SELECT id,code,name,neighborhood,address,phone,active FROM colheita.schools WHERE organization_id=:org AND (:q='' OR name ILIKE '%'||:q||'%' OR code ILIKE '%'||:q||'%') ORDER BY name LIMIT :size OFFSET :offset").param("org",org).param("q",q).param("size",size).param("offset",page*size).query((rs,n)->school(rs)).list();return new PageResult<>(items,total,page,size);}
    @Override public School saveSchool(UUID org,UUID id,String code,String name,String neighborhood,String address,String phone,boolean active){UUID result;if(id==null){result=jdbc.sql("INSERT INTO colheita.schools(organization_id,code,name,neighborhood,address,phone,active) VALUES(:org,:code,:name,:neighborhood,:address,:phone,:active) RETURNING id").param("org",org).param("code",code).param("name",name).param("neighborhood",neighborhood).param("address",address).param("phone",phone).param("active",active).query(UUID.class).single();}else{int changed=jdbc.sql("UPDATE colheita.schools SET code=:code,name=:name,neighborhood=:neighborhood,address=:address,phone=:phone,active=:active WHERE organization_id=:org AND id=:id").param("code",code).param("name",name).param("neighborhood",neighborhood).param("address",address).param("phone",phone).param("active",active).param("org",org).param("id",id).update();if(changed==0)throw DomainException.notFound("Escola não encontrada.");result=id;}return jdbc.sql("SELECT id,code,name,neighborhood,address,phone,active FROM colheita.schools WHERE organization_id=:org AND id=:id").param("org",org).param("id",result).query((rs,n)->school(rs)).single();}
    @Override public PageResult<Producer> listProducers(UUID org,String search,int page,int size){String q=q(search);long total=count("producers",org,q,"name","internal_id");var items=jdbc.sql("SELECT id,internal_id,name,document,phone,active FROM colheita.producers WHERE organization_id=:org AND (:q='' OR name ILIKE '%'||:q||'%' OR internal_id ILIKE '%'||:q||'%') ORDER BY name LIMIT :size OFFSET :offset").param("org",org).param("q",q).param("size",size).param("offset",page*size).query((rs,n)->producer(rs)).list();return new PageResult<>(items,total,page,size);}
    @Override public Producer saveProducer(UUID org,UUID id,String internalId,String name,String document,String phone,boolean active){UUID result;if(id==null){result=jdbc.sql("INSERT INTO colheita.producers(organization_id,internal_id,name,document,phone,active) VALUES(:org,:internal,:name,:document,:phone,:active) RETURNING id").param("org",org).param("internal",internalId).param("name",name).param("document",document).param("phone",phone).param("active",active).query(UUID.class).single();}else{int changed=jdbc.sql("UPDATE colheita.producers SET internal_id=:internal,name=:name,document=:document,phone=:phone,active=:active WHERE organization_id=:org AND id=:id").param("internal",internalId).param("name",name).param("document",document).param("phone",phone).param("active",active).param("org",org).param("id",id).update();if(changed==0)throw DomainException.notFound("Produtor não encontrado.");result=id;}return jdbc.sql("SELECT id,internal_id,name,document,phone,active FROM colheita.producers WHERE organization_id=:org AND id=:id").param("org",org).param("id",result).query((rs,n)->producer(rs)).single();}
    @Override public PageResult<ReturnReason> listReturnReasons(UUID org,String search,int page,int size){String q=q(search);long total=jdbc.sql("SELECT count(*) FROM colheita.return_reasons WHERE organization_id=:org AND (:q='' OR description ILIKE '%'||:q||'%')").param("org",org).param("q",q).query(Long.class).single();var items=jdbc.sql("SELECT id,code,description,active FROM colheita.return_reasons WHERE organization_id=:org AND (:q='' OR description ILIKE '%'||:q||'%') ORDER BY code LIMIT :size OFFSET :offset").param("org",org).param("q",q).param("size",size).param("offset",page*size).query((rs,n)->new ReturnReason(rs.getObject("id",UUID.class),rs.getInt("code"),rs.getString("description"),rs.getBoolean("active"))).list();return new PageResult<>(items,total,page,size);}
    @Override public ReturnReason saveReturnReason(UUID org,UUID id,int code,String description,boolean active){UUID result;if(id==null){result=jdbc.sql("INSERT INTO colheita.return_reasons(organization_id,code,description,active) VALUES(:org,:code,:description,:active) RETURNING id").param("org",org).param("code",code).param("description",description).param("active",active).query(UUID.class).single();}else{int changed=jdbc.sql("UPDATE colheita.return_reasons SET code=:code,description=:description,active=:active WHERE organization_id=:org AND id=:id").param("code",code).param("description",description).param("active",active).param("org",org).param("id",id).update();if(changed==0)throw DomainException.notFound("Motivo não encontrado.");result=id;}return jdbc.sql("SELECT id,code,description,active FROM colheita.return_reasons WHERE organization_id=:org AND id=:id").param("org",org).param("id",result).query((rs,n)->new ReturnReason(rs.getObject("id",UUID.class),rs.getInt("code"),rs.getString("description"),rs.getBoolean("active"))).single();}
    @Override public PageResult<Price> listPrices(UUID org,UUID productId,int page,int size){String filter=productId==null?"":" AND product_id=:product";var count=jdbc.sql("SELECT count(*) FROM colheita.prices WHERE organization_id=:org"+filter).param("org",org);if(productId!=null)count=count.param("product",productId);long total=count.query(Long.class).single();var query=jdbc.sql("SELECT id,product_id,price,valid_from,valid_to FROM colheita.prices WHERE organization_id=:org"+filter+" ORDER BY valid_from DESC LIMIT :size OFFSET :offset").param("org",org).param("size",size).param("offset",page*size);if(productId!=null)query=query.param("product",productId);var items=query.query((rs,n)->price(rs)).list();return new PageResult<>(items,total,page,size);}
    @Override public Price schedulePrice(UUID org,UUID productId,BigDecimal value,Instant from){jdbc.sql("UPDATE colheita.prices SET valid_to=:from WHERE organization_id=:org AND product_id=:product AND valid_to IS NULL AND valid_from<:from").param("from",from).param("org",org).param("product",productId).update();UUID id=jdbc.sql("INSERT INTO colheita.prices(organization_id,product_id,price,valid_from) VALUES(:org,:product,:price,:from) RETURNING id").param("org",org).param("product",productId).param("price",value).param("from",from).query(UUID.class).single();return jdbc.sql("SELECT id,product_id,price,valid_from,valid_to FROM colheita.prices WHERE id=:id").param("id",id).query((rs,n)->price(rs)).single();}
    private long count(String table,UUID org,String q,String c1,String c2){String sql="SELECT count(*) FROM colheita."+table+" WHERE organization_id=:org AND (:q='' OR "+c1+" ILIKE '%'||:q||'%' OR "+c2+" ILIKE '%'||:q||'%')";return jdbc.sql(sql).param("org",org).param("q",q).query(Long.class).single();}
    private UUID updateId(String table,UUID org,UUID id,Map<String,Object> values){String set=String.join(",",values.keySet().stream().map(k->k+"=:"+k).toList());var spec=jdbc.sql("UPDATE colheita."+table+" SET "+set+" WHERE organization_id=:org AND id=:id").param("org",org).param("id",id);for(var e:values.entrySet())spec=spec.param(e.getKey(),e.getValue());if(spec.update()==0)throw DomainException.notFound("Registro não encontrado.");return id;}
    private School school(ResultSet rs)throws java.sql.SQLException{return new School(rs.getObject("id",UUID.class),rs.getString("code"),rs.getString("name"),rs.getString("neighborhood"),rs.getString("address"),rs.getString("phone"),rs.getBoolean("active"));}
    private Producer producer(ResultSet rs)throws java.sql.SQLException{return new Producer(rs.getObject("id",UUID.class),rs.getString("internal_id"),rs.getString("name"),rs.getString("document"),rs.getString("phone"),rs.getBoolean("active"));}
    private Price price(ResultSet rs)throws java.sql.SQLException{var to=rs.getTimestamp("valid_to");return new Price(rs.getObject("id",UUID.class),rs.getObject("product_id",UUID.class),rs.getBigDecimal("price"),rs.getTimestamp("valid_from").toInstant(),to==null?null:to.toInstant());}
}
